version: "3"

services:

  headnode:
    build: headnode/

    command: python3 headnode.py
    
    volumes:
      - ./headnode/:/headnode/

  datanode1:
    build: datanode1/

    command: python3 datanode.py

    volumes:
      - ./datanode1/:/datanode/

    depends_on:
      - headnode
  
  datanode2:
    build: datanode2/

    command: python3 datanode.py

    volumes:
      - ./datanode2/:/datanode/

    depends_on:
      - headnode

  datanode3:
    build: datanode3/

    command: python3 datanode.py

    volumes:
      - ./datanode3/:/datanode/

    depends_on:
      - headnode

  client:
    build: client/

    volumes:
      - ./client/:/client/

    command: tail -f /dev/null

    depends_on:
      - headnode

